### ISSUE TITLE
yiksheng

### ISSUE THREAD

**Issue by yauyiksheng** [denikson/COM3D2.MaidFiddler#13]
**Error message**
Paste the error message in the area below:
```
Paste here
```

**To Reproduce**
Write a small description of what you tried to do (in GUI or the game).

**Version information:**
 - Game version [e.g. 1.19]
 - Maid Fiddler version [from *About Maid Fiddler* dialog]

**Additional context**
Add any other context about the problem here if there is any.

**Comment by denikson** [comment]
I assume this was a misclick. If you do have an issue, please fill in the information specified in the template.
