### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by J9J9v** [denikson/COM3D2.MaidFiddler#14]
**Error message**
Paste the error message in the area below:
```
Traceback (most recent call last):
  File "app.py", line 26, in <module>
  File "app.py", line 20, in main
  File "maidfiddler\ui\main_window.py", line 154, in connect
  File "maidfiddler\ui\tabs\player.py", line 105, in reload_player_props
  File "maidfiddler\ui\qt_elements.py", line 53, in set_value
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647

↓
Fatal error!
Failed to execute script app

```

**To Reproduce**
Write a small description of what you tried to do (in GUI or the game).

After launching the game, we loaded saved data and started the program, but when I clicked the screen, an error log appeared.(same as [https://github.com/denikson/COM3D2.MaidFiddler/issues/4])

**Version information:**
 - Game version （GP-01）[e.g. 1.28]
 - Maid Fiddler version [Version 1.0.4.3]

Thank you for continue to update.

**Comment by denikson** [comment]
Greetings!

Thank you for the information.  
I haven't been able to reproduce the problem, but I think I know where it is.

Could you try out this test version and whether it fixes the problem?
[MaidFiddlerSetup.zip](https://github.com/denikson/COM3D2.MaidFiddler/files/3075876/MaidFiddlerSetup.zip)

**Comment by J9J9v** [comment]
Thank you for your correspondence so quickly.

I tried test version ,it worked without errors!
Thank you very much.

*It seems reported error occurs when loaded the SaveData that activate compatibility mode with CM3D2.
