### ISSUE TITLE
Failed to launch

### ISSUE THREAD

**Issue by eiswort** [denikson/COM3D2.MaidFiddler#17]
**Error message**
Paste the error message in the area below:
```
Traceback (most recent call last):
  File "app.py", line 27, in <module>
  File "app.py", line 21, in main
  File "maidfiddler\ui\main_window.py", line 151, in connect
  File "maidfiddler\ui\tabs\ui_tab.py", line 25, in game_data
  File "maidfiddler\ui\tabs\maid_info.py", line 99, in update_ui
KeyError: 'additional_relation'
```

**To Reproduce**
Failed to connect to the game.
**Version information:**
 - Game version COM3D2 1.32.1 CM3D2 1.65
 - Maid Fiddler version Version 1.0.5.1

**Additional context**
Add any other context about the problem here if there is any.

**Comment by denikson** [comment]
Greetings!

Judging by the error, you have old version of Maid Fiddler plugin component installed.

You can check the version of your plugin component as follows:

1. Go to `<Game Directory>\Sybaris\UnityInjector` and find `COM3D2.MaidFiddler.Core.dll`
2. Right-click the found DLL and click the `Properties` from the appeared context menu
3. From the appeared window, select the `Details` tab.

Check that the version of the DLL is 1.0.5.1 as in this image:
![image](https://user-images.githubusercontent.com/13762037/62316959-5593e180-b4a1-11e9-808b-ec987bb930cd.png)

If it is not, I suggest rerunning the installer and making sure you select the **correct COM3D2 path**.

**Comment by eiswort** [comment]
Hi,

I doubt checked the version information and it is corrected but still not working

So I go ahead and reinstall the thing but it simply doesn't connect anymore.

**Comment by eiswort** [comment]
Did another reinstall on both BepInEx and Sybaris,it works again.
