### ISSUE TITLE
Describe the bug

### ISSUE THREAD

**Issue by EURIBIS12** [denikson/COM3D2.MaidFiddler#29]
**Describe the bug**
A clear and conci sedescription of what the bug is.

**To Reproduce**
A small description of what you tried to do.

**Expected behavior**

**Screenshots**

**Version info (please complete the following information):**
 - Game version [e.g. 1.19]
 - Maid Fiddler version [from *About Maid Fiddler* dialog]

**Additional context**

**Comment by denikson** [comment]
Empty issue, closing
