### ISSUE TITLE
something is wrong in Maid fiddler

### ISSUE THREAD

**Issue by ChaosSonic1** [denikson/COM3D2.MaidFiddler#39]
**Error message**
Maid Fiddler 1.0.7.3 only supports game version 1480 or newer.
This game's build version is 1470
```

**To Reproduce**
Updating Maid Fiddler

**Version information:**
 - Game version 1.053 (there is no new update in the current version)
 - Maid Fiddler version 1.07.3

**Additional context**
Add any other context about the problem here if there is any.

**Comment by denikson** [comment]
Greetings!

That is indeed correct, Maid Fiddler 1.0.7.3 only supports game build versions 1.48 or newer.

If you are playing the Japanese version of COM, [get the latest 1.48 update](http://com3d2.jp/update/)

If you are playing the English version, stay on 1.0.7.2 and ignore the update.  
If you have by accident already installed 1.0.7.3, you can simply reinstall 1.0.7.2 on top of 1.0.7.3.
