### ISSUE TITLE
Blackscreen on startup, GPU and CPU boost infinitely

### ISSUE THREAD

**Issue by Shrubgnome** [denikson/COM3D2.MaidFiddler#49]
Until today I ran Maid Fiddler V 1.0.6.0 together with COM3D2 Build 1.33 in a moderately modded BepInEx/Doorstop-Setup with no issues.
I decided to update to the newest COM3D2 Version, 106, and use it together with the newest corresponding Maid Fiddler version.

After installation, the game would no longer start up and get stuck in a black screen. During this blackscreen, my GPU will infinitely boost and my CPU also turbos a few cores.

Usually, starting the game barely has any performance impact.

Via trial and error I narrowed the offending file in the Sybaris folder down to Mono.Cecil.Inject.dll.

Once I remove it, the game launches and all other mods work, of course, but obviously the maid fiddler GUI is then non-functional after connecting to the game, crashing on any action.

The black screen does not throw any errors.

**To Reproduce**
Starting the game with the newest update to COM3D2, GP-01 and any MaidFiddler-Version.

**Screenshots**
_With injector (blackscreen)_
![With injector:](https://user-images.githubusercontent.com/69654380/90194029-8aca5380-ddc6-11ea-9056-00a71ef65aee.png)

_Without (ingame)_
![Without (ingame):](https://user-images.githubusercontent.com/69654380/90194295-3a072a80-ddc7-11ea-85d1-e550e2e67234.png)

**Version info**
Tested with COM3D2 Version 1.06.0 (Build 1.50) in combination with all of the following MaidFiddler-Versions:
- 1.0.6
- 1.0.7.2
- 1.0.8.1

**Additional information**
1) My Sybaris folder also contained Mono.Cecil.Rocks.dll.
I since removed it and, since the Maid Fiddler installer never generated it, assume it is inconsequential.

2) I updated my game in the first place because I bought a few DLC and figured such an old version that I had wouldn't run them. The DLC were installed via the game itself and I did let the Launcher finish up installation.

3) Probably related to issues #43 & #47, but the performance impact hadn't been mentioned yet, so I figured I'd chip in.

**Comment by denikson** [comment]
Greetings!

Judging by BepInEx versions and the messages seen, you might be used quite an old mod setup with potentially outdated plugins that might contribute to the problems. `Mono.Cecil.Inject.dll` is the core DLL used by Maid Fiddler to patch the game. Without it Maid Fiddler will not patch anything and thus is just skipped from loading (the only thing that gets loaded is the plugin part which becomes useless without the patcher). `Mono.Cecil.Inject.dll` is a known working DLL and not the real source of problems. Judging by your errors, it's more likely that you have unneeded/outdated DLLs in Sybaris folder.

I suggest using the COM Modular Installer for a working COM setup with latest BepInEx and other plugins: <https://drive.google.com/open?id=12R1lMuqlRPm-ioPXGm9IIKM3GxPCooUG>

The modular installer will clean up your current install and make backups of it. Having done that, you can try installing MF 1.0.8.1 which has been tested with 1.06 successfully. 

Finally, you might find better tech support related to your seemingly outdated BepInEx setup at COM Discord server: https://discord.gg/kfRy9T3

**Comment by Shrubgnome** [comment]
Yep, that did it. Thanks for the help and your work in general :)
