### ISSUE TITLE
Error on hiring new maid

### ISSUE THREAD

**Issue by nostalgiav3** [denikson/COM3D2.MaidFiddler#5]
**Error message**

```
Traceback (most recent call last):
  File "maidfiddler\ui\maids_list.py", line 31, in do_add_maid
NameError: name 'a' is not defined
```

**To Reproduce**

hire new maid
(in game "メイド管理" -> "雇用" -> "OK", and error occurred)

**Version information:**

 - Game version [1.19.1]
 - Maid Fiddler version [GUI: 1.0, Core: 1.0.0.0]

**Additional context**

None

**Comment by denikson** [comment]
Fix released in 1.0.1.0
