### ISSUE TITLE
Can't connect gui to com3d2

### ISSUE THREAD

**Issue by boylenovo** [denikson/COM3D2.MaidFiddler#57]
**Error message**
Paste the error message in the area below:

Paste here
[ERROR] : Failed to connect because [Errno 2] No such file or directory: '\\\\.\\pipe\\MaidFiddlerService'! Retrying in a second!

**To Reproduce**
I tried reinstalling but it didn't work.
Yesterday there was an update. But cannot connect as before.

**Version information:**
![Screenshot 2020-12-06 130414](https://user-images.githubusercontent.com/75557855/101272939-8259b680-37c3-11eb-9179-ca137d4e0cd8.png)

 - Game version [1.54]
 - Maid Fiddler version [1.0.8.2]

**Additional context**
None

**Comment by ghorsington** [comment]
Is your game running while you are connecting? You need to have COM running for Maid Fiddler to connect to it.

**Comment by Guntaboy** [comment]
Yes game running while I am connecting

**Comment by Guntaboy** [comment]
Oh it's my mistake. I can connect to it.
Sorry to bother you And thanks for helping

**Comment by ghorsington** [comment]
Good to know it works. Was it because the game wasn't fully loaded?

**Comment by Guntaboy** [comment]
I tried reinstalling sybaris. Then it will run normally
