### ISSUE TITLE
Yotogi skill names translation

### ISSUE THREAD

**Issue by derbayer36** [denikson/COM3D2.MaidFiddler#7]
**Describe the bug**
while all the yotogi skill names are translated in the game, some of them are not being translated in MaidFiddler Yotogi Skills menu

**Screenshots**
https://imgur.com/a/wJGkqIZ

**Version info (please complete the following information):**
 - Game version [1.20.1]
 - Maid Fiddler version [1.0.2.0]

**Additional context**
I think the Japanese text is translated using google translation add-on in the game but it doesn't appear in english in MaidFiddler.

**Comment by denikson** [comment]
Hey!

Pardon the very late reply -- I have been pretty busy, so I didn't have the time to answer!
This is normal behaviour of Maid Fiddler. The tool gets the names of yotogi skills directly from game without going through AutoTranslate or other translation loaders. Maid Fiddler has its own translation file that you can use to translate yotogi skills. This is done to mainly simplify the development of Maid Fiddler and still allow skills to be translated in some way.
