### ISSUE TITLE
GUI cannot connect to game

### ISSUE THREAD

**Issue by Lawrence510** [denikson/COM3D2.MaidFiddler#9]
**Describe the bug**
stuck at Connecting to COM3D2.

**To Reproduce**
I've tried to start the GUI without Sybaris installed on my com3d2

**Expected behavior**

**Screenshots**

**Version info (please complete the following information):**
 - Game version [e.g. 1.19]
 - Maid Fiddler version [from *About Maid Fiddler* dialog]

**Additional context**
###

**Comment by denikson** [comment]
Old issue, closing. Maid Fiddler has since been updated and the game as well. Please make sure your Maid Fiddler and game are up-to-date.

Please create a new issue if the problem still persists.
